---
services:
  acestream:
    container_name: acestream
    image: ghcr.io/2025devproton/acestream-http-proxy:latest
    restart: unless-stopped
    ports:
      - "6879:6879"
    environment:
      HTTP_PORT: 6879
      HTTPS_PORT: 6880
      BIND_ALL: "true"
